config/routes.rb
Rails.application.routes.draw do
  get 'movielistconnectors/controller'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :lists, except: [:edit, :update] do
    resources :movielistconnectors, only: [:new, :create]
  end
  resources :movielistconnectors, only: :destroy
  resources :movies, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :movielistconnectors, dependent: :destroy
  has_many :movies, through: :movielistconnectors
  has_many :reviews

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
has_many :movielistconnectors
has_many :lists, through: :movielistconnectors

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/movielistconnector.rb
class Movielistconnector < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    flash[:notice] = @bookmark.errors.full_messages.to_sentence unless @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  def index
    @list_card_covers = {}
    @list_card_covers[:zombies] = 'Dawn of the Dead'
    @list_card_covers[:animals] = 'Jaws'
    @list_card_covers[:aliens] = 'AVP: Alien vs. Predator'

    # Putting No category list at end
    @lists = List.all[1..List.count] << List.first
  end

  def show
    @list = List.find(params[:id])
    @list_movies = @list.movies
    @movies_in_list = @list_movies.page params[:page]
  end

  private

  def list_params
    params.require(:list).permit(:name, :overview)
  end
end

app/controllers/movielistconnectors_controller.rb
# frozen_string_literal: true

class MovielistconnectorsController < ApplicationController
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  def index
    @carousel_movie_titles = []
    @carousel_movie_titles[0] = 'The Shining'
    @carousel_movie_titles[1] = 'Alien'
    @carousel_movie_titles[2] = 'Saw II'
    @carousel_movie_titles[3] = 'A Nightmare on Elm Street'
    @carousel_movie_titles[4] = 'American Psycho'
    @carousel_movie_titles[5] = 'The Ring'

    @last_page = (Movie.all.length.to_f / 60).ceil

    if params[:query].present?
      sql_query = " \
        movies.title ILIKE :query \
        OR movies.release_date ILIKE :query \
        OR lists.name ILIKE :query \
      "
      @movies_total = Movie.joins(:lists).where(sql_query, query: "%#{params[:query]}%").count
      @movies = Movie.joins(:lists).where(sql_query, query: "%#{params[:query]}%").page params[:page]

    else
      @movies_total = Movie.all.count
      @movies = Movie.page params[:page]
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :rating, :poster_url, :release_date, :runtime, :id)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movielistconnectors_helper.rb
module MovielistconnectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application-old.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allgore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
  </head>

  <body>
    <%= yield %>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>All Gore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name=”description” content="Allgore. Horror in film.">
    <!-- Favicon -->
    <%= favicon_link_tag asset_path('allgore-logo.png') %>

    <!-- OG Facebook -->
    <meta property="og:url" content="http://allgore.herokuapp.com/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Allgore" />
    <meta property="og:description" content="Allgore. Horror in film." />
    <meta property="og:image" content="https://allgore.herokuapp.com/og-share-image2.png" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@flickr" />
    <meta name="twitter:title" content="Allgore" />
    <meta name="twitter:description" content="Allgore. Horror in film." />
    <meta name="twitter:image" content="https://allgore.herokuapp.com/og-share-image2.png" />

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    
  </head>
  <body class="background-color">
    <% if params[:controller] != "pages" && params[:action] != "home" %>
      <%= render 'shared/nav-top_bar' %>
    <% end %>
    <%= yield %>
    <!-- Footer -->
    <%= render 'shared/footer'  %>
  </body>


</html>

app/views/lists/index.html.erb
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>
<!-- movie list title section -->
<div class="ag-wrapper wireframe">
  <div class="ag-container wireframe">
    <h3 class="wireframe section-title white-text" style="padding-bottom: 20px;"><%= @lists.count %> subgenre lists on <span style="font-family: horrorFont; ">All Gore</span></h3>
  </div>
</div>
<!-- movie list cards -->
<div class="ag-wrapper wireframe">
  <div class="ag-container wireframe" style="overflow: visible;">
    <div class="lists-container wireframe" style="width: 100%;">
      <% @lists.each_with_index do |list, index| %>
        <div class="card wireframe" style="width: 100%; background: transparent;">
          <%= link_to list_path(list), class:'subgenre-card-link' do %>
              <% if @list_card_covers.include?(list.name.downcase.to_sym) == true %>
                <% list_with_desired_cover = list.movies.find_by title: @list_card_covers[list.name.downcase.to_sym] %> 
                <% list_card_image_url = list_with_desired_cover.backdrop_image_url %>
              <% else %>
                <% list_card_image_url = list.movies[0].backdrop_image_url %>
              <% end %>
              <img src="<%= list_card_image_url %>"class="list-card__backdrop-image" style="">
              <div class="subgenre-title-container wireframe" style="">
                <h4 class="subgenre-title subgenre-title__number"><%= index + 1 %></h4>
                <h4 class="subgenre-title subgenre-title__text wireframe"><%= list.name %></h4>
              </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Black Spacer -->
<%= render "shared/section_spacer" %>
<% %>

app/views/lists/new.html.erb
<div class="container py-5" style="background-color: yellow;">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Slasher' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>
<!-- movie list title section -->
<div class="ag-wrapper wireframe">
  <div class="ag-container wireframe">
    <h3 class="wireframe section-title white-text" style=""><span style="font-family: horrorFont;"><%= @list.name %></span></h3>
  </div>
</div>
<!-- Movies Index -->
<div class="ag-wrapper" style="overflow: visible;">
  <div class="ag-container" style="overflow: visible;">
    <div class="movies-container wireframe"style="">
      <% @movies_in_list.each do |movie| %>
        <div class="card" style="width: 100%; background: transparent;">
          <%= link_to movie_path(movie.id) do %>
            <div class="card wireframe">
              <% if movie.poster_url == "https://image.tmdb.org/t/p/w500/" %>
                <img src="<%= image_path('noposter.png') %>" class="movie-card__poster-image">
              <% else %>
                <svg xmlns="http://www.w3.org/2000/svg" class="movie-card__poster-proportion wireframe" preserveAspectRatio="xMidYMid meet" width="100%" fill="transparent" style="" viewBox="0 0 500 750"></svg>
                <img src="<%= movie.poster_url %>"class="movie-card__poster-image" style="">
              <% end %>
            </div>
          <% end %>
          <div class="movie-card__title-container wireframe" style="">
            <%= link_to movie_path(movie.id), style: 'position: relative; display: flex; text-decoration: none; float: left; width: fit-content;', class: '' do %>
              <!-- "https://www.themoviedb.org/movie/#{movie.tmdb_key}" -->
              <span class="movie-card__title wireframe", style="">
                <%= movie.title  %>
              </span>
            <% end %>
          </div>
          <!-- Release Date and Runtime -->
          <div class="movie-card__meta-data-container wireframe" style="">
            <span class="movie-card__meta-data" style=" "><%= movie.release_date[0..3] %>&nbsp; &#8226; &nbsp;<%= movie.runtime %> min</span>
          </div>
          <!-- Movie lists/horror subgenres -->
          <div class="movie-card__meta-data-container wireframe" style="">
            <% movie_lists_for_this_movie = [] %>
            <% movie.movielistconnectors.all.each do |movielistconnector| %>
              <% movie_lists_for_this_movie << List.find(movielistconnector.list_id).name if List.find(movielistconnector.list_id).name != "No Category" && List.find(movielistconnector.list_id).name != "" %>
            <% end %>
            <span class="movie-card__meta-data" style="float: right; display: <%= List.find(movie.movielistconnectors[0].list_id).name != "No Category" ? "block" : "none"  %>">
              <% movie_lists_for_this_movie.each do |movie_list_name| %>
                <% list_hash = List.find_by name: movie_list_name %>
                <%= link_to "##{movie_list_name}", list_path(list_hash.id), class: "movie-card__meta-data-link" %>&nbsp;
              <% end %>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Pagintation -->
<div class="ag-wrapper wireframe ">
  <div class="ag-container wireframe" style="align-items: center; justify-content: center; flex-direction: row; width: 100%; padding-top: 20px;">
    <div class="pagination">
      <%= paginate @movies_in_list, window: 2 %>
    </div>
  </div>
</div>
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>

app/views/movielistconnectors/controller.html.erb
<h1>Bookmarks#controller</h1>
<p>Find me in app/views/bookmarks/controller.html.erb</p>

app/views/movielistconnectors/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<!-- Banner Carousel -->
<%= render partial: 'shared/banner_carousel' if params[:query].present? == false && params[:page].to_i < 2 %>
<% %>
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>
<!-- movie list title section -->
<div class="ag-wrapper wireframe">
  <div class="ag-container wireframe">
    <% pagen = params[:page].to_i == 0 ? 1 : params[:page].to_i %>
    <h3 class="wireframe section-title white-text" style=""><%= (((pagen - 1) * 60) + 1) %> to <%= (pagen * 60) %> of <%= @movies_total %> movies on <span style="font-family: horrorFont;">All Gore</span></h3>
  </div>
</div>
<!-- Movies Index -->
<div class="ag-wrapper" style="overflow: visible;">
  <div class="ag-container" style="overflow: visible;">
    <div class="movies-container wireframe"style="">
      <% @movies.each do |movie| %>
        <div class="card" style="width: 100%; background: transparent;">
          <%= link_to movie_path(movie.id) do %>
            <div class="card wireframe">
              <% if movie.poster_url == "https://image.tmdb.org/t/p/w500/" %>
                <svg xmlns="http://www.w3.org/2000/svg" class="movie-card__poster-proportion wireframe" preserveAspectRatio="xMidYMid slice" width="100%" fill="transparent" style="" viewBox="0 0 500 750"></svg>
                <img src="<%= image_path('noposter.png') %>" class="movie-card__poster-image">
              <% else %>
                <svg xmlns="http://www.w3.org/2000/svg" class="movie-card__poster-proportion wireframe" preserveAspectRatio="xMidYMid slice" width="100%" fill="transparent" style="" viewBox="0 0 500 750"></svg>
                <img src="<%= movie.poster_url %>" class="movie-card__poster-image" style="">
              <% end %>
            </div>
          <% end %>
          <div class="movie-card__title-container wireframe" style="">
            <%= link_to movie_path(movie.id), style: 'position: relative; display: flex; text-decoration: none; float: left; width: fit-content;', class: '' do %>
              <span class="movie-card__title wireframe">
                <%= movie.title  %>
              </span>
            <% end %>
          </div>
          <!-- Release Date and Runtime -->
          <div class="movie-card__meta-data-container wireframe" style="">
            <span class="movie-card__meta-data"><%= movie.release_date[0..3] %>&nbsp; &#8226; &nbsp;<%= movie.runtime %> min</span>
          </div>
          <!-- Movie lists/horror subgenres -->
          <div class="movie-card__meta-data-container wireframe" style="">
            <% movie_lists_for_this_movie = [] %>
            <% movie.movielistconnectors.all.each do |movielistconnector| %>
              <% movie_lists_for_this_movie << List.find(movielistconnector.list_id).name if List.find(movielistconnector.list_id).name != "No Category" && List.find(movielistconnector.list_id).name != "" %>
            <% end %>
            <span class="movie-card__meta-data" style="float: right; display: <%= List.find(movie.movielistconnectors[0].list_id).name != "No Category" ? "block" : "none"  %>">
              <% movie_lists_for_this_movie.each do |movie_list_name| %>
                <% list_hash = List.find_by name: movie_list_name %>
                <%= link_to "##{movie_list_name}", list_path(list_hash.id), class: "movie-card__meta-data-link" %>&nbsp;
              <% end %>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Pagintation -->
<div class="ag-wrapper wireframe ">
  <div class="ag-container wireframe" style="align-items: center; justify-content: center; flex-direction: row; width: 100%; padding-top: 20px;">
    <div class="pagination">
      <%= paginate @movies, window: 2 %>
    </div>
  </div>
</div>
<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-color"  %>
<% %>

app/views/movies/show.html.erb
<div class="movie-show__landing-wrapper-background" id="" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.4) 0vh, rgba(0, 0, 0, 0.4) 60vh, rgba(0, 0, 0, 1) 100vh), url('<%= @movie[:backdrop_image_url] %>');">
</div>
<div class="ag-wrapper" style="">
  <div class="ag-container wireframe" style="width: 100%; overflow: visible;">
    <div class="top-container-after-nav-bar movie-show__movie-info-container wireframe" style="">   
        <!-- Flex Child 1 - left/top -->
        <div class="movie-show__movie-poster-image-container" style="position: relative; float: left; display: block;">            
          <img class="movie-show__movie-poster-image" src="<%= @movie[:poster_url] %>" style="top: 0px;"> 
        </div>
        <!-- Flex Child 2 - right/bottom -->
        <div class="movie-show__movie-title-etc wireframe" style="display: flex; flex-direction: column; background:">
          <h2 class="<%= @movie[:title].length > 18 ? "banner__movie-landing-title--long" : "banner__movie-landing-title" %> wireframe"><%= @movie[:title]  %></h2>
          <div style="position: relative; float: left; width: 100%;">  
            <span class="movie-show__movie-landing-year wireframe" style=" "><%= @movie.release_date[0..3] %>&nbsp; &#8226; &nbsp;<%= @movie.runtime %> min</span>
          </div>
          <p class="movie-show__movie-landing-tagline wireframe"><%= @movie.tagline %></p>
          <p class="movie-show__movie-landing-overview wireframe"><%= @movie.overview %></p>
          
          <div class="wireframe" style="position: relative; float: left; width: 100%; display: block;"> 
            <% movie_lists_for_this_movie = [] %>
            <% @movie.movielistconnectors.all.each do |movielistconnector| %>
              <% movie_lists_for_this_movie << List.find(movielistconnector.list_id).name if List.find(movielistconnector.list_id).name != "No Category" %>
            <% end %>
            <% movie_lists_for_this_movie.each_with_index do |movielist, index| %>
              <span class="movie-show__movie-lists wireframe" style="display: <%= List.find(@movie.movielistconnectors[index].list_id).name != "No Category" ? "block" : "none"  %>">
                <%= link_to movielist, list_path(@movie.movielistconnectors[index].list_id), class: "movie-show__list-link" %>
              </span>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

<!-- Black Spacer -->
<%= render "shared/section_spacer", background_color: "background-transparent"  %>
<% %>

<!-- Blackk Spacer -->
<%= render "shared/section_spacer", background_color: "background-transparent"  %>
<% %>

app/views/pages/home.html.erb
<!-- Background -->
<div class="landing-wrapper-background home-background" style="">
    <div class="ag-wrapper wireframe" style="position: relative;">
        <div class="ag-container window-height-height-minus-footer-height wireframe" style="display: flex; position: relative; float: left; width: 100%;">
            <!-- Home Content container -->
            <div class="top-container-after-nav-bar window-height-minus-nav-and-footer-height wireframe" style="">
                <div class="home-landing-container" style="">
                    <!-- Allgore Landing Title -->
                    <h1 class="home-landing__title" >
                        <%= render "shared/all-gore-full-text", display_class: "" %>
                    </h1>
                    <!-- Allgore search bar -->
                    <div class="home-landing__search-contaner" style="">
                        <%= render 'shared/searchbar', justify: "center" %>
                    </div>
                    <!-- Allgore CTAs-->
                    <div class="home_landing__ctas">
                        <%= link_to movies_path do %>
                            <span class="btn btn-danger mt-1 mr-2 banner__movie-link-button allgore-red-background" style="">
                                <span style="display: -webkit-box; max-width: 100%; -webkit-line-clamp: 1; -webkit-box-orient: vertical; overflow: hidden;">
                                    <span style="">Movies</span>
                                    <span> &nbsp; <i class="fas fa-chevron-right"></i></span>
                                </span>
                            </span>
                        <% end %>
                        <%= link_to lists_path do %>
                            <span class="btn btn-danger mt-1 banner__movie-link-button allgore-red-background">
                                <span style="display: -webkit-box; max-width: 100%; -webkit-line-clamp: 1; -webkit-box-orient: vertical; overflow: hidden;">
                                    <span style="">Lists</span>
                                    <span> &nbsp; <i class="fas fa-chevron-right"></i></span>
                                </span>
                            </span>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>

app/views/shared/_banner_carousel.html.erb
<div class="main-carousel">
  <!-- Carousel Item 1 -->
  <%= render partial: 'shared/banner_carousel_item', locals: {:banner_movie => @carousel_movie_titles[0]} %>
  <!-- Carousel Item 2 -->
  <%= render partial: 'shared/banner_carousel_item', locals: {:banner_movie => @carousel_movie_titles[1]} %>
  <!-- Carousel Item 3 -->
  <%= render partial: 'shared/banner_carousel_item', locals: {:banner_movie => @carousel_movie_titles[2]} %>
  <!-- Carousel Item 4 -->
  <%= render partial: 'shared/banner_carousel_item', locals: {:banner_movie => @carousel_movie_titles[3]} %>
  <!-- Carousel Item 5 -->
  <%= render partial: 'shared/banner_carousel_item', locals: {:banner_movie => @carousel_movie_titles[4]} %>
  <!-- Carousel Item 6 -->
  <%= render partial: 'shared/banner_carousel_item', locals: {:banner_movie => @carousel_movie_titles[5]} %>
</div>

app/views/shared/_banner_carousel_item.html.erb
<% banner_movie_instance = Movie.find { |movie| movie.title == banner_movie } %>
<% %>
<div class="carousel-cell landing-wrapper-background" id="" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0vh, rgba(0, 0, 0, 0) 60vh, rgba(0, 0, 0, 1) 100vh), url('<%= banner_movie_instance[:backdrop_image_url] %>');">
  <div class="ag-wrapper" style="">
    <div class="ag-container window-height wireframe" style="width: 100%; overflow: visible;">
      <div class="top-container-after-nav-bar window-height-minus-nav-height" style="">
        <div class="banner__movie-info-container wireframe">
          <!-- Flex Child 1 - left/top -->
          <div class="banner__movie-title-etc wireframe">
            <!-- Movie Title -->
            <h2 class="<%= banner_movie_instance[:title].length > 18 ? "banner__movie-landing-title--long" : "banner__movie-landing-title" %> wireframe"><%= banner_movie_instance[:title]  %></h2>
            <!-- Release Year -->
            <div class="relflowleft-container">
              <span class="banner__movie-landing-year wireframe" style=""><%= banner_movie_instance.release_date[0..3] %></span>
            </div>
            <!-- Tagline -->
            <p class="banner__movie-landing-tagline wireframe" style=""><%= banner_movie_instance.tagline %></p>
            <!-- Banner Movie link Button -->
            <div class="relflowleft-container">
              <%= link_to movie_path(banner_movie_instance.id) do %>
                <span class="btn btn-danger mt-1 banner__movie-link-button allgore-red-background">
                  <span style="display: -webkit-box; max-width: 100%; -webkit-line-clamp: 1; -webkit-box-orient: vertical; overflow: hidden;">
                    <span style="">
                      <%= banner_movie_instance.title %>
                    </span>
                    <span> 
                      &nbsp; <i class="fas fa-chevron-right"></i>
                    </span>
                  </span>
                </span>
              <% end %>
            </div>
          </div>
          <!-- Flex Child 2 - right/bottom -->
          <!-- Movie Poster -->
          <div class="banner__movie-poster wireframe">
            <img class="banner__movie-poster-image" src="<%= banner_movie_instance[:poster_url] %>" style="">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="ag-wrapper footer-height wireframe <%= "fixed-bottom" if params[:controller] == "pages" && params[:action] == "home" %>">
  <div class="ag-container footer-height wireframe" style="">
    <div class="footer-copyright" style="float: right; width: 100%;">
      <span style="color: #fff; float: right;">Made with <i class="fas fa-heart"></i> by <%= link_to "G. Perilli", "https://gperilli.dev/"%> </span>
    </div>
  </div>
</div>

app/views/shared/_nav-top_bar.html.erb
<div class="ag-wrapper wireframe" >
  <div class="fixed-top top-bar wireframe black_background">
    <!-- background opacity shifting rectangle -->
    <div id="test" class="navbar-background" style=""></div>
    <div class="ag-container wireframe" style="">
      <!-- brand home - hidden from top nav on small screens -->
      <%= render partial: 'shared/brand_logo_button', style: "z-index: 200;" %>
      <!-- Allgore search bar -->
      <% if params[:controller] != "pages" && params[:action] != "home" %>
        <%= render 'shared/searchbar', justify: "start" %>
      <% end %>
    </div>
  </div>
</div>
<!-- -->

app/views/shared/_searchbar.html.erb
 <!-- Allgore search bar -->
<div class="wireframe searchbar-main" style="justify-content: <%= justify %>">
  <%= form_tag movies_path, method: :get do %>
    <div class="ag-search-bar-container wireframe" style="">
      <%= text_field_tag :query,
      params[:query],
      class: "ag-search-bar__bar ag-font-main",
      placeholder: "movie, genre, year",
      autocomplete: "off"
      %>
      <%= button_tag(type: "Search", class: "ag-search-bar__button") do %>
        <i class="fas fa-search"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_section_spacer.html.erb
<div class="ag-wrapper wireframe">
  <div class="ag-container wireframe" style="height: 50px;">
  </div>
</div>